language: node_js
node_js: 
  - "4.1"
  - "0.12"

before_install:
  # Install web server
  #- "npm install -g node-web-server"
  # Background web server
  - "http-server &"
  # Sleep some time to nws lift
  - "sleep 5"

script: ./test_runner
