language: node_js
node_js: 
  - "4.1"
  - "0.12"

before_install:
  # Start xvfb
  # Set the xvfb screen size to 1280x1024x16
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

  # Install web server
  #- "npm install -g node-web-server"
  # Background web server
  - "http-server &"
  # Sleep some time to nws lift
  - "sleep 5"

script: ./test_runner
